#ifndef XLINSPEAK_VERSION_H
#define XLINSPEAK_VERSION_H

#define XLINSPEAK_VERSION_MAJOR 1
#define XLINSPEAK_VERSION_MINOR 3

#define XLINSPEAK_STRINGIFY2(x) #x
#define XLINSPEAK_STRINGIFY(x) XLINSPEAK_STRINGIFY2(x)

#define XLINSPEAK_VERSION \
  XLINSPEAK_STRINGIFY(XLINSPEAK_VERSION_MAJOR) "." \
  XLINSPEAK_STRINGIFY(XLINSPEAK_VERSION_MINOR)

#define XLINSPEAK_PLUGIN_NAME "XLinSpeak"

/* X-Plane treats the plugin signature as a stable plugin identifier. */
#define XLINSPEAK_PLUGIN_SIGNATURE "XLinSpeak v04"

#define XLINSPEAK_PLUGIN_DESCRIPTION "Speak up now (" XLINSPEAK_VERSION ")"

#endif
